config/routes.rb
  Devnation::Application.routes.draw do

  root 'static_pages#home'

  match '/about',  to: 'static_pages#about',  via: 'get'
  match '/atm', to: 'atm#show', via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/checking_accounts/deposit', to: 'checking_accounts#make_deposit', via: 'post'
  match '/checking_accounts/payment', to: 'checking_accounts#make_payment', via: 'post'
  match '/help',  to: 'static_pages#help',  via: 'get'
  match '/signup',  to: 'customers#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/atm/transaction', to: 'atm#create', via: 'post'

  resources :accounts
  resources :customers
  resources :sessions, only: [:new, :create, :destroy]
  resources :checking_accounts #, only: [:new, :create, :destroy]
  resources :transactions

end

app/models/checking_account.rb
class CheckingAccount < ActiveRecord::Base
	belongs_to :customer #, :class_name => "Customer", :foreign_key => "customer_id"
	has_many :withdrawls, :class_name => "Transaction", :foreign_key => "from_account_id", :primary_key => "account_number"
	has_many :deposits, :class_name => "Transaction", :foreign_key => "to_account_id", :primary_key => "account_number"
	validates :customer_id, presence: true

	#always generate a random account number
	after_create { 
		self.account_number = generate_account_number
		self.save
	 }

	def generate_account_number
		self.account_number = "DNB" + Random.rand(12345678).to_s
	end

	def all_transactions
		return Array.new(self.withdrawls + self.deposits)
	end

	def withdraw(amount)
		self.balance -= amount
	end

	def deposit(amount)
		self.balance += amount
	end
end

app/controllers/checking_accounts_controller.rb
class CheckingAccountsController < ApplicationController

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.find(params[:customer_id])
    @account = @customer.checking_accounts.create()

    # return back to the Customer's page
    respond_to do |format|
      if @account
        flash[:success] = "Welcome to DevNation Bank, #{@customer.first_name}!"
        format.html { redirect_to @customer, notice: 'Checking account was successfully created!' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'show', location: @customer }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @checking_account = CheckingAccount.find(params[:id])
    @transaction = Transaction.new
  end

  def show
    @checking_account = CheckingAccount.find(params[:id])
  end

  def make_deposit
    transaction_params = params[:transaction]
    @checking_account = CheckingAccount.find(transaction_params[:to_account])
    @transaction = Transaction.new
    @transaction.to_account_id = @checking_account.account_number
    @transaction.amount = transaction_params[:amount]
    @transaction.transaction_type = "deposit"
    @checking_account.balance += @transaction.amount

    begin
      @transaction.transaction do
        success = @transaction.save!
        success = @checking_account.save!      
      end 
      # on error return the error pae
      rescue => e
        respond_to do |format|
            format.html { render action: 'edit' }
            format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      return
    end

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to edit_checking_account_path(@checking_account.id), notice: "Deposit was successfully made.  Your account has been credited #{@transaction.amount}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def make_payment
    transaction_params = params[:transaction]

    @checking_account = CheckingAccount.find_by_account_number(transaction_params[:from_account])
    
    #build Transaction
    @transaction = Transaction.new
    @transaction.to_account_id = transaction_params[:to_account_id]
    @transaction.from_account_id = @checking_account.account_number
    @transaction.amount = transaction_params[:amount]
    @transaction.transaction_type = "payment"   
    @checking_account.balance = @checking_account.balance - @transaction.amount

    begin
      @transaction.transaction do
        success = @transaction.save!
        success = @checking_account.save!      
      end 
      # on error return the error pae
      rescue => e
        respond_to do |format|
            format.html { render action: 'edit' }
            format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      return
    end

    respond_to do |format|
        format.html { redirect_to edit_checking_account_path(@checking_account.id), notice: "Deposit was successfully made.  Your account has been credited #{@transaction.amount}" }
        format.json { head :no_content }
    end
  end

  def update
    @checking_account = CheckingAccount.find(params[:id])
    respond_to do |format|
      if @checking_account.update_attributes(checking_account_params)
        format.html { redirect_to @checking_account, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @checking_account.errors, status: :unprocessable_entity }
      end
    end
  end

    def checking_account_params
      params.require(:checking_account).permit(:balance)
    end

end

app/views/checking_accounts/_deposit_form.html.erb
<h1>Make Deposit</h1>
<%= form_for(@transaction, url: checking_accounts_deposit_path) do |f| %>
<!-- hidden fields -->
<%= f.hidden_field(:transaction_type, value: "deposit") %>
<%= f.hidden_field(:to_account, value: @checking_account.id) %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount, "Deposit Amount" %><br>
    <%= f.text_field :amount, id: "deposit_amount" %>
  </div>
  <div class="actions">
    <%= f.submit "Make Deposit", class: "btn" %>
  </div>
<% end %>

app/views/checking_accounts/_form.html.erb
<h1>Adjust Balance</h1>
<%= form_for(@checking_account) do |f| %>

  <% if @checking_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checking_account.errors.count, "error") %> prohibited the changes from being saved :

      <ul>
      <% @checking_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :balance %><br>
    <%= f.number_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit "Adjust Balance", class: "btn" %>
  </div>
<% end %>

app/views/checking_accounts/_payment_form.html.erb
<h1>Make Payment</h1>
<%= form_for(@transaction, url: checking_accounts_payment_path) do |f| %>
<!-- hidden fields -->
<%= f.hidden_field(:transaction_type, value: "payment") %>
<%= f.hidden_field(:from_account, value: @checking_account.account_number) %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_account_id %><br>
    <%= f.text_field :to_account_id, id: "to_account" %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, id: "payment_amount" %>
  </div>
  <div class="actions">
    <%= f.submit "Make Payment", class: "btn" %>
  </div>
<% end %>

app/views/checking_accounts/edit.html.erb
<% provide(:title, @checking_account.account_number) %>
<h1>Account <%= @checking_account.account_number %></h1>

<%= render 'deposit_form' %>
<br/>
<%= render 'payment_form' %>
<br/>
<%= render 'form' %>
<br/>

<%= link_to 'Show', @checking_account %> |
<%= link_to 'Back', checking_accounts_path %>

app/views/checking_accounts/show.html.erb
<% provide(:title, @checking_account.account_number) %>

<p id="notice"><%= notice %></p>

<h2>Account : <%= @checking_account.account_number %></h2>
<p>
  <strong>Balance:</strong>
  <%= @checking_account.balance %>
</p>