config/routes.rb
  Devnation::Application.routes.draw do

  root 'static_pages#home'

  match '/about',  to: 'static_pages#about',  via: 'get'
  match '/atm', to: 'atm#show', via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/checking_accounts/deposit', to: 'checking_accounts#make_deposit', via: 'post'
  match '/checking_accounts/payment', to: 'checking_accounts#make_payment', via: 'post'
  match '/help',  to: 'static_pages#help',  via: 'get'
  match '/signup',  to: 'customers#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/atm/transaction', to: 'atm#create', via: 'post'

  resources :accounts
  resources :customers
  resources :sessions, only: [:new, :create, :destroy]
  resources :checking_accounts #, only: [:new, :create, :destroy]
  resources :transactions

end

app/models/customer.rb
class Customer < ActiveRecord::Base

	#always downcase email address to ensure uniqueness
	before_save { self.email = email.downcase }

	validates :first_name, presence: true
	validates :last_name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  	has_secure_password
	has_many :accounts
	has_many :checking_accounts
	validates :password, length: { minimum: 6 }

	def name
		return "#{first_name} #{last_name}"
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    print @customer

    respond_to do |format|
      if @customer.save
        flash[:success] = "Welcome to DevNation Bank, #{@customer.first_name}!"
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :gender, :password, :password_confirmation)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Gender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.gender %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<% provide(:title, 'Signup') %>

<h1>Signup</h1>

<div class="row" >
	<div class="span6 offset3" >
		<%= render 'shared/error_messages' %>
		<%= form_for(@customer) do |c| %>

			<%= c.label :first_name %>
			<%= c.text_field :first_name %>
			
			<%= c.label :last_name %>
			<%= c.text_field :last_name %>

			<%= c.label :email %>
			<%= c.text_field :email %>

			<%= c.label :gender %>
			<%= c.text_field :gender %>

			<%= c.label :password %>
			<%= c.password_field :password %>

			<%= c.label :password_confirmation, "Confirm Password" %>
			<%= c.password_field :password_confirmation %>

			<%= c.submit "Signup", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>
<% @customer.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
<% end %>
<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<% provide(:title, @customer.name) %>

<p id="notice"><%= notice %></p>

<h2>Personal</h2>
<p>
  <strong>Name:</strong>
  <%= @customer.first_name %>   <%= @customer.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @customer.gender %>
</p>

<%= form_tag("/checking_accounts", method: "post") do %>
	<%= hidden_field_tag(:customer_id, @customer.id) %>
	<%= submit_tag "Add Checking Account", class: "btn", name: "add_checking_account"	 %>
  <!-- , :name: "add_checking_account", :class: "btn btn-large btn-primary" -->
<% end %>

<h2>Accounts</h2>
<% if @customer.checking_accounts.any? %>

	<h3><% @customer.checking_accounts.count %> Checking <% pluralize(@customer.checking_accounts, 'Account') %></h3>
    <% @customer.checking_accounts.each do |account| %>
		<p><strong>Account Number:</strong><%= account.account_number %></p>
		<p><strong>Balance:</strong><%= account.balance %></p>
    <p><%= link_to 'Account Actions', edit_checking_account_path(account), class: "btn", id: "#{account.id}_actions" %></p>
    <% end %>

<% end %>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>