config/routes.rb
  Devnation::Application.routes.draw do

  root 'static_pages#home'

  match '/about',  to: 'static_pages#about',  via: 'get'
  match '/atm', to: 'atm#show', via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/checking_accounts/deposit', to: 'checking_accounts#make_deposit', via: 'post'
  match '/checking_accounts/payment', to: 'checking_accounts#make_payment', via: 'post'
  match '/help',  to: 'static_pages#help',  via: 'get'
  match '/signup',  to: 'customers#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/atm/transaction', to: 'atm#create', via: 'post'

  resources :accounts
  resources :customers
  resources :sessions, only: [:new, :create, :destroy]
  resources :checking_accounts #, only: [:new, :create, :destroy]
  resources :transactions

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from_account_id, :to_account_id, :amount, :timestamp)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_type_deposit, "Deposit" %>
    <%= f.radio_button(:transaction_type, "deposit") %>
  </div>
  <div class="field">
    <%= f.label :transaction_type_withdrawl, "Withdrawl" %>
    <%= f.radio_button(:transaction_type, "withdrawl", :checked => true) %>
  </div>
  <div class="field">
    <%= f.label :from_account_id %><br>
    <%= f.text_field :from_account_id %>
  </div>
  <div class="field">
    <%= f.label :to_account_id %><br>
    <%= f.text_field :to_account_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit "Create Transaction", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<% provide(:title, "DevNation Bank Transactions") %>

<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>From account</th>
      <th>To account</th>
      <th>Amount</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.from_account_id %></td>
        <td><%= transaction.to_account_id %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<% provide(:title, 'DevNation Bank Transactions') %>

<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From account:</strong>
  <%= @transaction.from_account_id %>
</p>

<p>
  <strong>To account:</strong>
  <%= @transaction.to_account_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @transaction.transaction_type %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>