config/routes.rb
  Devnation::Application.routes.draw do

  root 'static_pages#home'

  match '/about',  to: 'static_pages#about',  via: 'get'
  match '/atm', to: 'atm#show', via: 'get'
  match '/contact',  to: 'static_pages#contact',  via: 'get'
  match '/checking_accounts/deposit', to: 'checking_accounts#make_deposit', via: 'post'
  match '/checking_accounts/payment', to: 'checking_accounts#make_payment', via: 'post'
  match '/help',  to: 'static_pages#help',  via: 'get'
  match '/signup',  to: 'customers#new',  via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/atm/transaction', to: 'atm#create', via: 'post'

  resources :accounts
  resources :customers
  resources :sessions, only: [:new, :create, :destroy]
  resources :checking_accounts #, only: [:new, :create, :destroy]
  resources :transactions

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    DevNation Rails site based on <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Contact", 'contact_path' %></li>
      <li><a href="http://devnation.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "DevNation Bank", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "Help", help_path %></li>
						<% if current_customer %>
							<li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
						<% else %>
							<li><%= link_to "Sign In", signin_path %></li>
							<li><%= link_to "Sign Up", signup_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>